Better checks in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -94,6 +94,10 @@ if [ -z "$BOOST_SYSTEM" ]; then
         BOOST_SYSTEM=-lboost_system
     elif [ -r /usr/lib/libboost_system-mt.so ]; then
         BOOST_SYSTEM=-lboost_system-mt.so
+    else
+        echo "Cannot find boost_system-mt.so (or boost_system.so)"
+        echo "Specify it with --boost_system or install libboost-dev-all."
+        exit 1
     fi
 fi
 # boost_filesystem is also somewhat a pain
@@ -102,6 +106,10 @@ if [ -z "$BOOST_FILESYSTEM" ]; then
         BOOST_FILESYSTEM=-lboost_filesystem
     elif [ -r /usr/lib/libboost_filesystem-mt.so ]; then
         BOOST_FILESYSTEM=-lboost_filesystem-mt
+    else
+        echo "Cannot find boost_filesystem-mt.so (or boost_filesystem.so)"
+        echo "Specify it with --boost_filesystem or install libboost-dev-all."
+        exit 1
     fi
 fi
 if [ -z "$STATGRAB" ]; then
@@ -109,6 +117,10 @@ if [ -z "$STATGRAB" ]; then
         STATGRAB=-lstatgrab
     elif [ -r /usr/local/lib/libstatgrab.so ]; then
         STATGRAB=-lstatgrab
+    else
+        echo "Cannot find libstatgrab.so"
+        echo "Specify it with --statgrab or install libstatgrab-dev."
+        exit 1
     fi
 fi
 if [ -z "$LIBRT" ]; then
@@ -116,6 +128,9 @@ if [ -z "$LIBRT" ]; then
         LIBRT=-lrt
     elif [ -r /usr/local/lib/librt.so ]; then
         LIBRT=-lrt
+    else
+        echo "Cannot find librt.so"
+        echo "Specify it with --librt"
     fi
 fi
 
