add libboost-iostreams dependency to configure and fix some libboost readme / console innacuracies

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,6 +24,7 @@ echo "# makevars.config for istatd generated on " `date` > makevars.config
 BOOST_SYSTEM=""
 BOOST_FILESYSTEM=""
 BOOST_THREAD=""
+BOOST_IOSTREAMS=""
 STATGRAB=""
 LIBRT=""
 DESTDIR=""
@@ -44,6 +45,10 @@ while [ $# -gt 0 ]; do
         --boost_thread)
             shift
             BOOST_THREAD="$1"
+            ;;
+        --boost_iostreams)
+            shift
+            BOOST_IOSTREAMS="$1"
             ;;
         --statgrab)
             shift
@@ -74,6 +79,7 @@ while [ $# -gt 0 ]; do
             echo "--boost_system     -lboost_system-mt      What is the boost_system library name?"
             echo "--boost_filesystem -lboost_filesystem-mt  What is the boost_filesystem library name?"
             echo "--boost_thread     -lboost_thread-mt      What is the boost_thread library name?"
+            echo "--boost_iostreams  -lboost_iostreams-mt   What is the boost_iostreams library name?"
             echo "--statgrab         -lstatgrab             What is the statgrab library name?"
             echo "--librt            -lrt                   What is the librt library name (if any)?"
             echo "--prefix           /                      What is the root of the install?"
@@ -89,7 +95,7 @@ done
 
 # see if we need to install boost
 if [ ! -d /usr/include/boost -a ! -d /usr/local/include/boost ]; then
-    echo "You need to install libboost-dev-all for your distribution."
+    echo "You need to install libboost-all-dev for your distribution."
     exit 1
 fi
 
@@ -119,7 +125,7 @@ if [ -z "$BOOST_SYSTEM" ]; then
     BOOST_SYSTEM=`findone -lboost_system -lboost_system-mt`
     if [ -z "$BOOST_SYSTEM" ]; then
         echo "Cannot find boost_system-mt.so (or boost_system.so)"
-        echo "Specify it with --boost_system or install libboost-dev-all."
+        echo "Specify it with --boost_system or install libbost-all-dev."
         exit 1
     fi
 fi
@@ -128,7 +134,7 @@ if [ -z "$BOOST_FILESYSTEM" ]; then
     BOOST_FILESYSTEM=`findone -lboost_filesystem -lboost_filesystem-mt`
     if [ -z "$BOOST_FILESYSTEM" ]; then
         echo "Cannot find boost_filesystem-mt.so (or boost_filesystem.so)"
-        echo "Specify it with --boost_filesystem or install libboost-dev-all."
+        echo "Specify it with --boost_filesystem or install libbost-all-dev."
         exit 1
     fi
 fi
@@ -138,7 +144,16 @@ if [ -z "$BOOST_THREAD" ]; then
     BOOST_THREAD=`findone -lboost_thread -lboost_thread-mt`
     if [ -z "$BOOST_THREAD" ]; then
         echo "Cannot find boost_thread-mt.so (or boost_thread.so)"
-        echo "Specify it with --boost_thread or install libboost-dev-all."
+        echo "Specify it with --boost_thread or install libbost-all-dev."
+        exit 1
+    fi
+fi
+
+if [ -z "$BOOST_IOSTREAMS" ]; then
+    BOOST_IOSTREAMS=`findone -lboost_iostreams -lboost_iostreams-mt`
+    if [ -z "$BOOST_IOSTREAMS" ]; then
+        echo "Cannot find boost_iostreams-mt.so (or boost_iostreams.so)"
+        echo "Specify it with --boost_iostreams or install libbost-all-dev."
         exit 1
     fi
 fi
@@ -174,6 +189,9 @@ if [ ! -z "$BOOST_FILESYSTEM" ]; then
 fi
 if [ ! -z "$BOOST_THREAD" ]; then
     echo "BOOST_THREAD=$BOOST_THREAD" >> makevars.config
+fi
+if [ ! -z "$BOOST_IOSTREAMS" ]; then
+    echo "BOOST_IOSTREAMS=$BOOST_IOSTREAMS" >> makevars.config
 fi
 if [ ! -z "$STATGRAB" ]; then
     echo "STATGRAB=$STATGRAB" >> makevars.config
